### ISSUE TITLE
Duplicate rows intoduced by normalising measures aren't deduplicated

### ISSUE THREAD

**Issue by jbothma** [openspending/datapackage-pipelines-fiscal#7]
In order to submit an issue, please ensure you can check the following. Thanks!

* [ ] Declare which version of Python you are using (`python --version`)
* [ ] Declare which operating system you are using

for the dataset
```csv
econ_1,2013/14 Audited outcome,2014/15 Audited outcome
A,123,0
A,0,0
```
the spec (ignoring sources and fields)
```yaml
measures:
  currency: ZAR
  title: Amount
  mapping:
    "2013/14 Audited outcome":
      budget_phase: "Audited Outcome"
      financial_year: "2013"
    "2014/15 Audited outcome":
      budget_phase: "Audited Outcome"
      financial_year: "2014"

deduplicate: true
```
produces a fiscal data package which has duplicate primary keys.

I think this is because deduplication happens before measure normalisation, and measure normalisation introduces two rows with key `A,2014,Audited Outcome,0`
